import { Widget } from "./types";

interface ScriptedResponse {
  chunks: string[];
  widgets: Widget[];
}

export const scriptedResponses: Record<string, ScriptedResponse> = {
  "vp-1": {
    chunks: [
      "# 🏖️ Lịch Du Lịch Nha Trang 3 Ngày 2 Đêm - Lễ 30/4\n\n",
      "Wow, Nha Trang dịp lễ 30/4 là lựa chọn cực kỳ tuyệt vời! ",
      "Mình đã lên sẵn lịch trình khám phá trọn vẹn cho bạn rồi nè. ",
      "Cùng xem bản đồ các điểm đến trước nhé:\n\n",
      "<<WIDGET:map>>\n\n",
      "Mình chia lịch trình thành 3 ngày, mỗi ngày một trải nghiệm khác nhau — từ nghỉ dưỡng, khám phá đến mua sắm. Đây là chi tiết:\n\n",
      "<<WIDGET:itinerary>>\n\n",
      "💰 **Chi phí ước tính:** khoảng 8-12 triệu VNĐ/người, đã bao gồm vé máy bay, khách sạn, ăn uống và vé tham quan.\n\n",
      "Bạn muốn mình giúp đặt phòng khách sạn hay tìm vé máy bay giá tốt luôn không? 😊",
    ],
    widgets: [
      {
        id: "w-map-1",
        type: "map",
        title: "Bản đồ Du lịch Nha Trang",
        data: {
          center: { lat: 12.2388, lng: 109.1967 },
          zoom: 13,
          markers: [
            { lat: 12.2388, lng: 109.1967, label: "Bãi biển Trần Phú", color: "#0EA5E9" },
            { lat: 12.2226, lng: 109.248, label: "VinPearl Resort", color: "#10B981" },
            { lat: 12.245, lng: 109.19, label: "Chợ Đầm", color: "#F97316" },
            { lat: 12.17, lng: 109.28, label: "Hòn Mun", color: "#8B5CF6" },
          ],
        },
      },
      {
        id: "w-itin-1",
        type: "itinerary",
        title: "Lịch trình 3 ngày Nha Trang",
        data: {
          days: [
            {
              day: 1,
              title: "Đón Nha Trang",
              items: [
                { time: "08:00", activity: "Bay đến Cam Ranh", icon: "✈️" },
                { time: "11:00", activity: "Check-in VinPearl Resort", icon: "🏨" },
                { time: "12:30", activity: "Bún chả cá Thanh Hiền", icon: "🍜" },
                { time: "14:00", activity: "Tắm biển Trần Phú", icon: "🏊" },
                { time: "18:00", activity: "Phố đi bộ & hải sản", icon: "🌅" },
              ],
            },
            {
              day: 2,
              title: "Khám Phá",
              items: [
                { time: "09:00", activity: "Công viên VinWonders", icon: "🎢" },
                { time: "15:00", activity: "Thủy cung VinPearl", icon: "🐠" },
                { time: "19:00", activity: "Show nhạc nước", icon: "🎵" },
              ],
            },
            {
              day: 3,
              title: "Trải Nghiệm",
              items: [
                { time: "07:00", activity: "Lặn ngắm san hô Hòn Mun", icon: "🤿" },
                { time: "11:00", activity: "Mua sắm chợ Đầm", icon: "🛍️" },
                { time: "14:00", activity: "Bay về", icon: "✈️" },
              ],
            },
          ],
        },
      },
    ],
  },
  "vp-2": {
    chunks: [
      "# 🏨 Resort phù hợp gia đình ở Phú Quốc\n\n",
      "Phú Quốc là thiên đường cho gia đình luôn đó bạn! ",
      "Mình đã chọn ra 3 resort có tiện ích trẻ em tốt nhất — xem vị trí trên bản đồ trước nhé:\n\n",
      "<<WIDGET:map>>\n\n",
      "**Top 3 resort mình gợi ý:**\n\n",
      "1. **VinPearl Resort & Golf** — 5⭐ từ 4.200.000đ/đêm\n",
      "   Bãi biển riêng, câu lạc bộ trẻ em, kết nối thẳng VinWonders luôn!\n\n",
      "2. **InterContinental Phú Quốc** — 5⭐ từ 5.800.000đ/đêm\n",
      "   Có chương trình Planet Trekkers siêu thú vị cho bé\n\n",
      "3. **Novotel Phú Quốc** — 4⭐ từ 2.800.000đ/đêm\n",
      "   Giá hợp lý nhất, phòng gia đình rộng rãi\n\n",
      "Gia đình bạn dự tính đi ngày nào? Mình kiểm tra phòng trống cho nhé! 🏖️",
    ],
    widgets: [
      {
        id: "w-map-2",
        type: "map",
        title: "Bản đồ Resort Phú Quốc",
        data: {
          center: { lat: 10.29, lng: 103.98 },
          zoom: 11,
          markers: [
            { lat: 10.32, lng: 103.86, label: "VinPearl Resort", color: "#0EA5E9" },
            { lat: 10.17, lng: 104.01, label: "InterContinental", color: "#10B981" },
            { lat: 10.21, lng: 103.96, label: "Novotel", color: "#F97316" },
          ],
        },
      },
    ],
  },
  "mu-1": {
    chunks: [
      "# 🎧 Playlist Lo-Fi Chill cho Đêm Code Khuya\n\n",
      "Đêm nay lại thức code đúng không? Mình hiểu cảm giác đó lắm! ",
      "Đây là playlist mình chọn lọc kỹ — toàn bài có BPM chậm, ít lời hát, giúp bạn vào \"zone\" nhanh hơn:\n\n",
      "<<WIDGET:playlist>>\n\n",
      "**Vì sao playlist này hiệu quả:**\n",
      "- 🎵 Dải BPM 70-85 — vùng tối ưu cho tập trung sâu\n",
      "- 🎹 Không có lời hát gây phân tâm\n",
      "- 🌙 Âm thanh ấm áp, dễ chịu cho đêm khuya\n\n",
      "Tổng thời lượng khoảng **2 tiếng** — đủ cho một phiên code đỉnh cao. ",
      "Bạn thích thể loại nào khác thì bảo mình điều chỉnh nhé! 🎶",
    ],
    widgets: [
      {
        id: "w-playlist-1",
        type: "playlist",
        title: "Nhạc Lo-Fi Code Đêm Khuya",
        data: {
          tracks: [
            { title: "Snowfall", artist: "Øneheart & Reidenshi", duration: "2:14", bpm: 75 },
            { title: "Coffee Shop Vibes", artist: "Lo-Fi Dreamer", duration: "3:42", bpm: 80 },
            { title: "Midnight Rain", artist: "Sleepy Fish", duration: "2:58", bpm: 72 },
            { title: "2:00 AM Study Session", artist: "Mondo Loops", duration: "3:15", bpm: 78 },
            { title: "Tokyo Night Drive", artist: "DJ Autumn", duration: "4:01", bpm: 82 },
            { title: "Rainy Day in Seoul", artist: "Tomppabeats", duration: "2:45", bpm: 76 },
            { title: "Floating", artist: "Idealism", duration: "3:20", bpm: 70 },
            { title: "Quiet Moments", artist: "Kupla", duration: "2:55", bpm: 74 },
          ],
          mood: "chill",
          totalDuration: "2h 15m",
        },
      },
    ],
  },
  "fo-1": {
    chunks: [
      "# 🍲 Quán Phở Ngon Nhất Quận 1, TP.HCM\n\n",
      "Ồ, phở Quận 1 thì mình rành lắm! ",
      "Sau khi tổng hợp đánh giá từ hàng nghìn review, đây là 3 quán đỉnh nhất mà bạn nên thử:\n\n",
      "<<WIDGET:restaurant>>\n\n",
      "Mình đánh dấu vị trí các quán trên bản đồ để bạn dễ tìm đường nhé:\n\n",
      "<<WIDGET:map>>\n\n",
      "Mẹo nhỏ: Nếu đi vào buổi sáng sớm (trước 8h) thì không cần xếp hàng đâu! ",
      "Bạn muốn mình chỉ đường đến quán nào, hay tìm thêm quán phở phù hợp chế độ ăn riêng? 🍜",
    ],
    widgets: [
      {
        id: "w-rest-1",
        type: "restaurant",
        title: "So sánh nhà hàng",
        data: {
          restaurants: [
            {
              name: "Phở Hòa Pasteur",
              rating: 4.5,
              price: "55-85K",
              specialty: "Phở Sài Gòn cổ điển từ 1968",
              hours: "6:00 - 24:00",
              distance: "0.8 km",
            },
            {
              name: "Phở Lệ",
              rating: 4.4,
              price: "65-95K",
              specialty: "Nước dùng ninh xương 12 tiếng",
              hours: "6:00 - 22:00",
              distance: "2.1 km",
            },
            {
              name: "Phở Thìn Bò Hồ",
              rating: 4.3,
              price: "60-80K",
              specialty: "Phở Hà Nội bò xào tái lăn",
              hours: "6:30 - 21:00",
              distance: "1.2 km",
            },
          ],
        },
      },
      {
        id: "w-map-3",
        type: "map",
        title: "Phở ngon nhất Quận 1",
        data: {
          center: { lat: 10.776, lng: 106.695 },
          zoom: 14,
          markers: [
            { lat: 10.7821, lng: 106.694, label: "Phở Hòa Pasteur", color: "#EF4444" },
            { lat: 10.754, lng: 106.664, label: "Phở Lệ", color: "#F97316" },
            { lat: 10.779, lng: 106.7, label: "Phở Thìn Bò Hồ", color: "#10B981" },
          ],
        },
      },
    ],
  },
  "sh-1": {
    chunks: [
      "# 📱 So sánh iPhone 15 Pro Max vs Samsung Galaxy S24 Ultra\n\n",
      "Đây là hai \"ông vua\" flagship hiện tại luôn! Để mình phân tích giúp bạn chọn đúng máy nhé. ",
      "Trước tiên, xem so sánh giá từ các cửa hàng uy tín:\n\n",
      "<<WIDGET:shopping>>\n\n",
      "**Mình đánh giá nhanh từng tiêu chí:**\n",
      "- 🏆 **Hiệu năng:** Hòa — A17 Pro và Snapdragon 8 Gen 3 đều mạnh như nhau\n",
      "- 📷 **Camera:** Samsung thắng thông số (200MP!), nhưng iPhone ổn định và màu thật hơn\n",
      "- 📱 **Màn hình:** Samsung nhỉnh hơn với 6.8\" QHD+\n",
      "- 🤖 **AI:** Samsung đang dẫn trước với Galaxy AI, Circle to Search\n\n",
      "**Gợi ý của mình:** Nếu bạn đang xài MacBook, AirPods thì iPhone là lựa chọn hoàn hảo. ",
      "Còn nếu thích camera zoom xa và nhiều tính năng AI thì Samsung sẽ hợp hơn.\n\n",
      "Bạn đang nghiêng về máy nào? Mình tìm deal tốt nhất cho bạn! 🔥",
    ],
    widgets: [
      {
        id: "w-shop-1",
        type: "shopping",
        title: "So sánh giá",
        data: {
          products: [
            {
              name: "iPhone 15 Pro Max 256GB",
              prices: [
                { store: "Apple Store", price: "34.990.000đ", url: "#" },
                { store: "Thế Giới Di Động", price: "33.490.000đ", url: "#" },
                { store: "CellphoneS", price: "32.990.000đ", url: "#" },
              ],
              image: "iphone",
            },
            {
              name: "Samsung Galaxy S24 Ultra 256GB",
              prices: [
                { store: "Samsung Store", price: "33.990.000đ", url: "#" },
                { store: "Thế Giới Di Động", price: "31.990.000đ", url: "#" },
                { store: "FPT Shop", price: "31.490.000đ", url: "#" },
              ],
              image: "samsung",
            },
          ],
        },
      },
    ],
  },
  "fi-1": {
    chunks: [
      "# 💪 Kế Hoạch Tập Luyện 4 Tuần Tại Nhà\n\n",
      "Chào mừng bạn bắt đầu hành trình fitness! ",
      "Mình thiết kế chương trình này đặc biệt cho người mới — bắt đầu nhẹ nhàng, tăng dần mỗi tuần. ",
      "Không cần mua dụng cụ gì hết, chỉ cần bạn và một khoảng trống nhỏ thôi!\n\n",
      "Đây là lịch tập tuần đầu tiên:\n\n",
      "<<WIDGET:itinerary>>\n\n",
      "**Tổng quan chương trình:**\n",
      "- ⏱️ 4 tuần, tập 4 ngày/tuần (nghỉ T4, T7, CN)\n",
      "- 🕐 Mỗi buổi chỉ 25-40 phút thôi\n",
      "- 📈 Mỗi tuần tăng thêm 2 reps/set và 5 giây cho bài giữ\n\n",
      "**Mẹo từ mình:** Đừng quên uống đủ 2 lít nước/ngày, ngủ 7-8 tiếng để cơ phục hồi, ",
      "và chụp ảnh tiến trình mỗi thứ Hai — bạn sẽ bất ngờ với sự thay đổi sau 4 tuần đấy! 💪\n\n",
      "Sẵn sàng chưa? Mình có thể hướng dẫn chi tiết từng động tác Ngày 1 luôn nè!",
    ],
    widgets: [
      {
        id: "w-itin-2",
        type: "itinerary",
        title: "Lịch tập Tuần 1",
        data: {
          days: [
            {
              day: 1,
              title: "Thứ 2 - Thân Trên",
              items: [
                { time: "5 phút", activity: "Xoay tay & giãn cơ", icon: "🔄" },
                { time: "3x10", activity: "Chống đẩy biến thể", icon: "💪" },
                { time: "3x30s", activity: "Plank giữ", icon: "🧘" },
                { time: "3x10", activity: "Hít tay tricep (ghế)", icon: "🪑" },
                { time: "5 phút", activity: "Giãn cơ hồi phục", icon: "🧘‍♀️" },
              ],
            },
            {
              day: 2,
              title: "Thứ 3 - Thân Dưới",
              items: [
                { time: "5 phút", activity: "Khởi động động", icon: "🔄" },
                { time: "3x12", activity: "Squat", icon: "🦵" },
                { time: "3x10", activity: "Lunge đi bộ", icon: "🚶" },
                { time: "3x15", activity: "Nâng hông", icon: "🍑" },
                { time: "5 phút", activity: "Giãn cơ chân", icon: "🧘‍♂️" },
              ],
            },
          ],
        },
      },
    ],
  },
  "la-1": {
    chunks: [
      "# 🇻🇳 Câu Chào Hỏi Cơ Bản Tiếng Việt\n\n",
      "Xin chào! Rất vui vì bạn muốn học tiếng Việt! 🎉 ",
      "Tiếng Việt có 6 thanh điệu nghe hơi \"scary\" — nhưng đừng lo, mình sẽ bắt đầu từ những câu đơn giản và thực tế nhất.\n\n",
      "## Những câu bạn sẽ dùng nhiều nhất\n\n",
      "| Tiếng Việt | Tiếng Anh | Phát âm |\n",
      "|-----------|---------|-------------------|\n",
      "| Xin chào | Hello | sin chow |\n",
      "| Cảm ơn | Thank you | gahm uhn |\n",
      "| Xin lỗi | Sorry | sin loy |\n",
      "| Tạm biệt | Goodbye | tahm bee-et |\n",
      "| Vâng/Dạ | Yes | vuhng/yah |\n",
      "| Không | No | kohm |\n\n",
      "## Câu giao tiếp thân thiện\n",
      "- **Tôi tên là...** (toy ten lah) — My name is...\n",
      "- **Bạn khỏe không?** (bahn kwe kohm) — How are you?\n",
      "- **Tôi khỏe, cảm ơn** — I'm fine, thank you\n",
      "- **Rất vui được gặp bạn** — Nice to meet you\n\n",
      "## 🎯 Bí kíp giao tiếp\n",
      "Người Việt rất thích khi bạn biết dùng đúng đại từ theo tuổi:\n",
      "- **Anh/Chị** cho người lớn tuổi hơn (thể hiện sự tôn trọng)\n",
      "- **Em** cho người nhỏ tuổi hơn\n",
      "- **Bạn** cho bạn bè cùng tuổi\n\n",
      "Bạn muốn thử luyện tập với một tình huống thực tế không? Ví dụ mình có thể đóng vai đi mua phở! 🍜",
    ],
    widgets: [],
  },
  "we-1": {
    chunks: [
      "# 🌤️ Thời Tiết Đà Lạt Cuối Tuần Này\n\n",
      "Đà Lạt cuối tuần này trời khá lý tưởng cho một chuyến đi đấy! Để mình check dự báo cho bạn:\n\n",
      "<<WIDGET:weather>>\n\n",
      "Nhìn chung là **mát mẻ và dễ chịu** — rất hợp để tận hưởng ngoài trời!\n\n",
      "## 🎯 Mình gợi ý lịch trình theo thời tiết\n",
      "- ☀️ **Sáng thứ 7:** Leo đỉnh Langbiang khi trời còn quang (view siêu đẹp!)\n",
      "- 🌿 **Chiều thứ 7:** Khám phá thác Datanla — mát lắm\n",
      "- 🌧️ **Sáng chủ nhật:** Có thể mưa nhẹ → tranh thủ đi cà phê hopping\n",
      "- 🌅 **Chiều chủ nhật:** Ngắm hoàng hôn ở Hồ Xuân Hương trước khi về\n\n",
      "**Nhớ mang theo:** áo khoác nhẹ (15-22°C buổi tối se lạnh), ô gấp gọn, giày đi bộ thoải mái, và kem chống nắng (tia UV ở vùng cao vẫn mạnh đấy!).\n\n",
      "Bạn cần mình lên kế hoạch chi tiết hơn cho cuối tuần không? 🌿",
    ],
    widgets: [
      {
        id: "w-weather-1",
        type: "weather",
        title: "Dự Báo Cuối Tuần Đà Lạt",
        data: {
          location: "Đà Lạt, Lâm Đồng",
          days: [
            {
              day: "Thứ 7",
              high: 22,
              low: 15,
              condition: "Có mây",
              icon: "⛅",
              humidity: 65,
              rain: 10,
            },
            {
              day: "Chủ nhật",
              high: 20,
              low: 14,
              condition: "Mưa nhẹ",
              icon: "🌧️",
              humidity: 78,
              rain: 60,
            },
          ],
        },
      },
    ],
  },
  "vp-3": {
    chunks: [
      "# 🎯 Hoạt Động Hay Nhất Ở Đà Nẵng Cuối Tuần Này\n\n",
      "Đà Nẵng cuối tuần này có nhiều thứ vui lắm bạn ơi! ",
      "Mình vừa tổng hợp những hoạt động đáng trải nghiệm nhất — xem bản đồ để hình dung vị trí nhé:\n\n",
      "<<WIDGET:map>>\n\n",
      "Để bạn không bỏ lỡ gì, mình xếp lịch trình gọn gàng theo từng buổi luôn nè:\n\n",
      "<<WIDGET:itinerary>>\n\n",
      "**Tips từ dân địa phương:**\n",
      "- 🌊 Biển Mỹ Khê đẹp nhất lúc bình minh (5:30 sáng) — ít người, sóng êm\n",
      "- 🌉 Cầu Rồng phun lửa và nước vào **21:00 thứ 7 và chủ nhật** — đừng quên!\n",
      "- 🍻 Khu phố An Thượng sôi động nhất sau 19:00\n\n",
      "Bạn đi một mình hay đi nhóm? Mình sẽ gợi ý thêm hoạt động phù hợp cho bạn! 😄",
    ],
    widgets: [
      {
        id: "w-map-4",
        type: "map",
        title: "Bản đồ Hoạt động Đà Nẵng",
        data: {
          center: { lat: 16.047, lng: 108.206 },
          zoom: 13,
          markers: [
            { lat: 16.058, lng: 108.247, label: "Biển Mỹ Khê", color: "#0EA5E9" },
            { lat: 16.061, lng: 108.227, label: "Cầu Rồng", color: "#EF4444" },
            { lat: 16.069, lng: 108.245, label: "Phố An Thượng", color: "#F97316" },
            { lat: 16.002, lng: 108.263, label: "Bán đảo Sơn Trà", color: "#10B981" },
            { lat: 15.994, lng: 108.019, label: "Bà Nà Hills", color: "#8B5CF6" },
          ],
        },
      },
      {
        id: "w-itin-3",
        type: "itinerary",
        title: "Lịch trình cuối tuần Đà Nẵng",
        data: {
          days: [
            {
              day: 1,
              title: "Thứ 7 - Khám Phá",
              items: [
                { time: "05:30", activity: "Ngắm bình minh tại Mỹ Khê", icon: "🌅" },
                { time: "08:00", activity: "Ăn sáng mì Quảng Bà Mua", icon: "🍜" },
                { time: "09:30", activity: "Trekking bán đảo Sơn Trà", icon: "🐒" },
                { time: "14:00", activity: "Bà Nà Hills & Cầu Vàng", icon: "🏰" },
                { time: "21:00", activity: "Xem Cầu Rồng phun lửa", icon: "🐉" },
              ],
            },
            {
              day: 2,
              title: "Chủ Nhật - Thư Giãn",
              items: [
                { time: "07:00", activity: "Lướt sóng tại Mỹ Khê", icon: "🏄" },
                { time: "10:00", activity: "Chợ Hàn mua quà", icon: "🛍️" },
                { time: "12:00", activity: "Hải sản Bé Mặn", icon: "🦐" },
                { time: "15:00", activity: "Check-in Ngũ Hành Sơn", icon: "⛰️" },
              ],
            },
          ],
        },
      },
    ],
  },
  "mu-2": {
    chunks: [
      "# 🚗 Playlist V-Pop Road Trip Cực Đỉnh\n\n",
      "Road trip mà thiếu nhạc V-pop thì phí cả chuyến đi! ",
      "Mình chọn toàn bài \"quẩy trên xe\" — đảm bảo ai cũng hát theo được luôn:\n\n",
      "<<WIDGET:playlist>>\n\n",
      "**Tại sao mình chọn những bài này:**\n",
      "- 🎤 Mix giữa ballad nhẹ nhàng và bản hit sôi động, phù hợp đi đường dài\n",
      "- 🛣️ Sắp xếp theo \"mood\" — bắt đầu chill, lên dần rồi hạ nhẹ cuối playlist\n",
      "- 🎵 Tổng thời lượng ~1 tiếng 40 phút — vừa đủ cho một chặng đường\n\n",
      "Bạn muốn mình thêm nhạc của nghệ sĩ nào khác vào playlist không? Hay tạo thêm playlist cho chặng đường về? 🎶",
    ],
    widgets: [
      {
        id: "w-playlist-2",
        type: "playlist",
        title: "V-Pop Road Trip 2024",
        data: {
          tracks: [
            { title: "Waiting For You", artist: "MONO", duration: "4:05", bpm: 90 },
            { title: "See Tình", artist: "Hoàng Thùy Linh", duration: "3:23", bpm: 115 },
            { title: "Đi Về Nhà", artist: "Đen Vâu ft. JustaTee", duration: "4:12", bpm: 95 },
            { title: "Có Hẹn Với Thanh Xuân", artist: "MONSTAR", duration: "3:45", bpm: 108 },
            { title: "Nàng Thơ", artist: "Hoàng Dũng", duration: "4:30", bpm: 82 },
            { title: "Dù Cho Mai Về Sau", artist: "buitruonglinh", duration: "3:58", bpm: 100 },
            { title: "Chúng Ta Của Hiện Tại", artist: "Sơn Tùng M-TP", duration: "4:15", bpm: 88 },
            { title: "Đừng Làm Trái Tim Anh Đau", artist: "Sơn Tùng M-TP", duration: "3:35", bpm: 120 },
          ],
          mood: "upbeat",
          totalDuration: "1h 40m",
        },
      },
    ],
  },
  "mu-3": {
    chunks: [
      "# 🔥 K-Pop Trending Tuần Này\n\n",
      "K-pop tuần này sôi động dữ lắm bạn ơi! ",
      "Mình tổng hợp các bài đang viral trên các BXH lớn — nghe thử xem bạn đã biết bài nào chưa:\n\n",
      "<<WIDGET:playlist>>\n\n",
      "**Điểm nổi bật tuần này:**\n",
      "- 👑 **BLACKPINK** và **aespa** đang cạnh tranh top 1 quyết liệt\n",
      "- 🆕 Bài mới của **Stray Kids** debut ngay #3 — fandom mạnh thật sự\n",
      "- 💜 BTS vẫn giữ vững vị trí dù đang hiatus\n\n",
      "Bạn là fan nhóm nào? Mình có thể tạo playlist riêng cho bias của bạn luôn nè! 💖",
    ],
    widgets: [
      {
        id: "w-playlist-3",
        type: "playlist",
        title: "K-Pop Hot Tuần Này",
        data: {
          tracks: [
            { title: "Supernova", artist: "aespa", duration: "3:08", bpm: 130 },
            { title: "APT.", artist: "ROSÉ ft. Bruno Mars", duration: "2:42", bpm: 148 },
            { title: "Chk Chk Boom", artist: "Stray Kids", duration: "3:22", bpm: 140 },
            { title: "Magnetic", artist: "ILLIT", duration: "2:58", bpm: 125 },
            { title: "EASY", artist: "LE SSERAFIM", duration: "3:15", bpm: 118 },
            { title: "Armageddon", artist: "aespa", duration: "3:30", bpm: 135 },
            { title: "Love Me Like This", artist: "NMIXX", duration: "3:05", bpm: 122 },
            { title: "Smart", artist: "LE SSERAFIM", duration: "2:55", bpm: 128 },
          ],
          mood: "energetic",
          totalDuration: "1h 05m",
        },
      },
    ],
  },
  "fo-2": {
    chunks: [
      "# 🕯️ Nhà Hàng Lãng Mạn Ở Phố Cổ Hà Nội\n\n",
      "Ôi, hẹn hò ở phố cổ là lựa chọn lãng mạn tuyệt vời đấy! ",
      "Mình chọn ra 3 nhà hàng có không gian cực kỳ ấm cúng và món ăn xuất sắc:\n\n",
      "<<WIDGET:restaurant>>\n\n",
      "Mình đánh dấu vị trí trên bản đồ để hai bạn dễ dạo phố cổ rồi ghé ăn luôn nhé:\n\n",
      "<<WIDGET:map>>\n\n",
      "**Mẹo cho buổi hẹn hoàn hảo:**\n",
      "- 🕖 Đặt bàn trước 17:00 để có chỗ đẹp nhất (gần cửa sổ nhìn ra phố)\n",
      "- 🌃 Sau bữa ăn, đi bộ ra Hồ Hoàn Kiếm ngắm đêm — siêu romantic!\n",
      "- 🍷 The Hanoi Social Club có cocktail craft rất đặc biệt\n\n",
      "Bạn muốn mình đặt bàn luôn không? Hay cần gợi ý thêm quán cà phê cho after-dinner? 💕",
    ],
    widgets: [
      {
        id: "w-rest-2",
        type: "restaurant",
        title: "Nhà hàng lãng mạn phố cổ",
        data: {
          restaurants: [
            {
              name: "The Hanoi Social Club",
              rating: 4.6,
              price: "150-350K",
              specialty: "Fusion Việt-Âu, không gian vintage 3 tầng",
              hours: "8:00 - 23:00",
              distance: "Phố Hội Vũ",
            },
            {
              name: "Madame Hiên",
              rating: 4.7,
              price: "200-450K",
              specialty: "Ẩm thực Việt fine-dining trong biệt thự Pháp cổ",
              hours: "11:00 - 22:00",
              distance: "Phố Chân Cầm",
            },
            {
              name: "La Badiane",
              rating: 4.5,
              price: "300-600K",
              specialty: "French-Vietnamese fusion, sân vườn lãng mạn",
              hours: "11:30 - 14:00, 18:00 - 22:00",
              distance: "Phố Nam Ngư",
            },
          ],
        },
      },
      {
        id: "w-map-5",
        type: "map",
        title: "Bản đồ nhà hàng phố cổ Hà Nội",
        data: {
          center: { lat: 21.033, lng: 105.852 },
          zoom: 15,
          markers: [
            { lat: 21.033, lng: 105.849, label: "The Hanoi Social Club", color: "#EC4899" },
            { lat: 21.037, lng: 105.847, label: "Madame Hiên", color: "#8B5CF6" },
            { lat: 21.028, lng: 105.849, label: "La Badiane", color: "#F97316" },
            { lat: 21.029, lng: 105.852, label: "Hồ Hoàn Kiếm", color: "#0EA5E9" },
          ],
        },
      },
    ],
  },
  "fo-3": {
    chunks: [
      "# 👨‍🍳 Công Thức Bánh Mì Thịt Heo Quay Giòn\n\n",
      "Bánh mì thịt heo quay — đỉnh cao ẩm thực đường phố Việt Nam! ",
      "Mình chia sẻ công thức đã thử và chỉnh sửa nhiều lần, đảm bảo da giòn rụm luôn nhé:\n\n",
      "<<WIDGET:recipe>>\n\n",
      "**Bí quyết da giòn \"bách phát bách trúng\":**\n",
      "- 🧂 Chấm da bằng xiên nhọn thật kỹ — càng nhiều lỗ da càng giòn\n",
      "- 💨 Quạt khô da trong tủ lạnh qua đêm (bước quan trọng nhất!)\n",
      "- 🔥 15 phút cuối tăng lửa 230°C để da phồng rộp\n\n",
      "Thời gian chuẩn bị hơi lâu nhưng kết quả xứng đáng lắm bạn! ",
      "Bạn muốn mình hướng dẫn thêm cách làm đồ chua và pate gan không? 🥖",
    ],
    widgets: [
      {
        id: "w-recipe-1",
        type: "recipe",
        title: "Bánh Mì Thịt Heo Quay Giòn",
        data: {
          servings: 6,
          prepTime: "30 phút + ướp qua đêm",
          cookTime: "1 tiếng 30 phút",
          difficulty: "Trung bình",
          ingredients: [
            "1kg thịt ba chỉ (ba rọi) có da",
            "2 muỗng canh muối hột",
            "1 muỗng canh ngũ vị hương",
            "3 tép tỏi băm nhuyễn",
            "1 muỗng canh nước mắm",
            "1 muỗng cà phê tiêu trắng",
            "Giấm trắng (để thoa da)",
            "6 ổ bánh mì giòn",
            "Rau mùi, dưa leo, ớt, đồ chua",
          ],
          steps: [
            "Rửa sạch thịt, dùng xiên chọc thật nhiều lỗ trên da",
            "Trộn muối, ngũ vị hương, tỏi, nước mắm, tiêu — ướp phần thịt (không dính da)",
            "Thoa giấm lên da, để tủ lạnh không đậy nắp qua đêm cho da khô",
            "Nướng 180°C trong 1 tiếng 15 phút",
            "Tăng lửa 230°C, nướng thêm 15 phút cho da giòn phồng",
            "Để nguội 10 phút, xắt miếng vừa ăn",
            "Kẹp vào bánh mì cùng đồ chua, rau mùi, dưa leo và tương ớt",
          ],
        },
      },
    ],
  },
  "sh-2": {
    chunks: [
      "# ⌨️ Bàn Phím Cơ Tốt Nhất Dưới 2 Triệu Đồng\n\n",
      "Bạn chọn đúng mức giá rồi đó — 2 triệu là sweet spot cho bàn phím cơ chất lượng! ",
      "Mình đã so sánh hơn 20 model và chọn ra top 3 đáng mua nhất:\n\n",
      "<<WIDGET:shopping>>\n\n",
      "**Mình chọn giúp bạn theo nhu cầu:**\n",
      "- 💻 **Làm việc/gõ văn bản:** Royal Kludge RK84 — switch brown êm ái, layout compact\n",
      "- 🎮 **Gaming:** FL Esports K210 — switch linear nhanh, full-size có numpad\n",
      "- 🎨 **Đẹp + Chill:** AKKO 3068B — hotswap, keycap PBT, có Bluetooth 5.0\n\n",
      "Bạn dùng bàn phím chủ yếu để làm gì? Mình sẽ gợi ý switch phù hợp luôn! ⌨️",
    ],
    widgets: [
      {
        id: "w-shop-2",
        type: "shopping",
        title: "Bàn phím cơ dưới 2 triệu",
        data: {
          products: [
            {
              name: "Royal Kludge RK84 (Switch Brown)",
              prices: [
                { store: "Shopee Mall", price: "1.290.000đ", url: "#" },
                { store: "Phong Vũ", price: "1.390.000đ", url: "#" },
                { store: "Lazada", price: "1.250.000đ", url: "#" },
              ],
              image: "keyboard",
            },
            {
              name: "FL Esports K210 RGB",
              prices: [
                { store: "Shopee Mall", price: "1.490.000đ", url: "#" },
                { store: "GearVN", price: "1.590.000đ", url: "#" },
                { store: "Lazada", price: "1.450.000đ", url: "#" },
              ],
              image: "keyboard",
            },
            {
              name: "AKKO 3068B Plus (Multi-mode)",
              prices: [
                { store: "AKKO Official", price: "1.790.000đ", url: "#" },
                { store: "Shopee Mall", price: "1.690.000đ", url: "#" },
                { store: "Tiki", price: "1.750.000đ", url: "#" },
              ],
              image: "keyboard",
            },
          ],
        },
      },
    ],
  },
  "sh-3": {
    chunks: [
      "# ✨ Skincare Tốt Nhất Cho Da Dầu\n\n",
      "Da dầu thì mình hiểu nỗi khổ lắm — bóng nhờn, lỗ chân lông to, dễ nổi mụn! ",
      "Đây là những sản phẩm được cộng đồng skincare Việt đánh giá cao nhất cho da dầu:\n\n",
      "<<WIDGET:shopping>>\n\n",
      "**Routine gợi ý cho da dầu:**\n",
      "- 🌅 **Sáng:** Sữa rửa mặt → Toner → Serum Niacinamide → Kem chống nắng\n",
      "- 🌙 **Tối:** Tẩy trang dầu → Sữa rửa mặt → BHA 2% (2-3 lần/tuần) → Kem dưỡng ẩm gel\n\n",
      "**Lưu ý quan trọng:**\n",
      "- 💧 Da dầu vẫn cần dưỡng ẩm nhé — thiếu ẩm da tiết dầu nhiều hơn đấy\n",
      "- ☀️ Kem chống nắng là bước KHÔNG được bỏ — chọn loại kiềm dầu\n\n",
      "Bạn đang gặp vấn đề gì nhất với da? Mụn, bóng dầu, hay lỗ chân lông to? Mình tư vấn chi tiết hơn nhé! 🧴",
    ],
    widgets: [
      {
        id: "w-shop-3",
        type: "shopping",
        title: "Skincare cho da dầu",
        data: {
          products: [
            {
              name: "Cerave Foaming Cleanser 236ml",
              prices: [
                { store: "Guardian", price: "295.000đ", url: "#" },
                { store: "Shopee Mall", price: "275.000đ", url: "#" },
                { store: "Hasaki", price: "289.000đ", url: "#" },
              ],
              image: "skincare",
            },
            {
              name: "The Ordinary Niacinamide 10% + Zinc 1%",
              prices: [
                { store: "Shopee Mall", price: "230.000đ", url: "#" },
                { store: "Lazada", price: "245.000đ", url: "#" },
                { store: "Hasaki", price: "250.000đ", url: "#" },
              ],
              image: "skincare",
            },
            {
              name: "Skin1004 Madagascar Centella Tone Brightening Capsule Sun Cream SPF50+",
              prices: [
                { store: "Shopee Mall", price: "320.000đ", url: "#" },
                { store: "Guardian", price: "355.000đ", url: "#" },
                { store: "Hasaki", price: "335.000đ", url: "#" },
              ],
              image: "skincare",
            },
          ],
        },
      },
    ],
  },
  "fi-2": {
    chunks: [
      "# 🥗 Ăn Gì Trước Và Sau Khi Chạy Bộ Buổi Sáng?\n\n",
      "Câu hỏi hay lắm! Dinh dưỡng đúng cách sẽ giúp bạn chạy khỏe hơn và phục hồi nhanh hơn nhiều.\n\n",
      "## ☀️ Trước khi chạy (30-60 phút trước)\n",
      "Mục tiêu: **Năng lượng nhanh, dễ tiêu hóa**\n\n",
      "- 🍌 **1 quả chuối** — nguồn carb tốt nhất cho runner\n",
      "- 🍞 **1 lát bánh mì nguyên cám + mật ong** — carb chậm + đường tự nhiên\n",
      "- 🥣 **Yến mạch + sữa hạnh nhân** — nếu chạy sau 1 tiếng ăn\n",
      "- ☕ **1 ly cà phê đen** (tùy chọn) — tăng hiệu suất 10-15%\n\n",
      "⚠️ **Tránh:** Đồ nhiều chất béo, sữa tươi (dễ đau bụng), đồ chiên rán\n\n",
      "## 💪 Sau khi chạy (trong vòng 30-45 phút)\n",
      "Mục tiêu: **Phục hồi cơ + nạp lại glycogen**\n\n",
      "- 🥚 **2 trứng luộc + 1 lát bánh mì** — protein + carb hoàn hảo\n",
      "- 🥤 **Sinh tố chuối + whey protein + sữa** — tiện và hiệu quả\n",
      "- 🍗 **Cơm gà + rau xanh** — bữa sáng đầy đủ nếu chạy sớm\n",
      "- 💧 **500ml nước** — bù nước là ưu tiên số 1!\n\n",
      "**Công thức vàng:** Tỷ lệ **3:1 carb:protein** sau khi chạy giúp phục hồi tối ưu.\n\n",
      "Bạn thường chạy bao nhiêu km? Mình sẽ tính toán lượng calo cụ thể cho bạn! 🏃",
    ],
    widgets: [],
  },
  "fi-3": {
    chunks: [
      "# ⏱️ Bài Tập HIIT 30 Phút Không Cần Dụng Cụ\n\n",
      "HIIT 30 phút — ngắn gọn nhưng đốt mỡ cực kỳ hiệu quả! ",
      "Mình thiết kế bài tập này gồm 5 round, mỗi round 4 bài, xen kẽ nghỉ hợp lý. Xem lịch trình chi tiết nhé:\n\n",
      "<<WIDGET:itinerary>>\n\n",
      "**Quy tắc thực hiện:**\n",
      "- ⚡ Mỗi bài tập: **40 giây cháy hết sức** → 20 giây nghỉ\n",
      "- 🔄 Giữa mỗi round: nghỉ **1 phút**\n",
      "- 💧 Uống nước trong lúc nghỉ giữa round\n\n",
      "**Lưu ý:**\n",
      "- 📈 Người mới: giảm xuống 30s tập / 30s nghỉ\n",
      "- 🔥 Có thể đốt **300-400 calo** trong 30 phút\n",
      "- 🚫 Không tập khi đói hoặc ngay sau ăn no\n\n",
      "Bạn muốn mình quay video hướng dẫn từng động tác, hay tạo thêm bài tập HIIT nâng cao? 💪",
    ],
    widgets: [
      {
        id: "w-itin-4",
        type: "itinerary",
        title: "HIIT 30 phút - Chi tiết",
        data: {
          days: [
            {
              day: 1,
              title: "Khởi động (5 phút)",
              items: [
                { time: "1 phút", activity: "Chạy tại chỗ", icon: "🏃" },
                { time: "1 phút", activity: "Jumping Jacks", icon: "⭐" },
                { time: "1 phút", activity: "Xoay hông & vai", icon: "🔄" },
                { time: "1 phút", activity: "High Knees nhẹ", icon: "🦵" },
                { time: "1 phút", activity: "Squat nhẹ khởi động", icon: "🧘" },
              ],
            },
            {
              day: 2,
              title: "Round 1-2 (10 phút)",
              items: [
                { time: "40s", activity: "Burpees", icon: "💥" },
                { time: "40s", activity: "Mountain Climbers", icon: "⛰️" },
                { time: "40s", activity: "Jump Squats", icon: "🦘" },
                { time: "40s", activity: "Push-up to Shoulder Tap", icon: "💪" },
                { time: "1 phút", activity: "--- Nghỉ giữa round ---", icon: "💧" },
              ],
            },
            {
              day: 3,
              title: "Round 3-4 (10 phút)",
              items: [
                { time: "40s", activity: "Tuck Jumps", icon: "🚀" },
                { time: "40s", activity: "Plank Jacks", icon: "🧘" },
                { time: "40s", activity: "Lunge Jumps xen kẽ", icon: "🦵" },
                { time: "40s", activity: "Bicycle Crunches", icon: "🚲" },
                { time: "1 phút", activity: "--- Nghỉ giữa round ---", icon: "💧" },
              ],
            },
            {
              day: 4,
              title: "Round 5 + Cool Down (5 phút)",
              items: [
                { time: "40s", activity: "High Knees nhanh", icon: "🔥" },
                { time: "40s", activity: "Spider-Man Push-ups", icon: "🕷️" },
                { time: "40s", activity: "Star Jumps", icon: "⭐" },
                { time: "40s", activity: "Plank hold", icon: "🧘" },
                { time: "3 phút", activity: "Giãn cơ & thở sâu", icon: "🧘‍♀️" },
              ],
            },
          ],
        },
      },
    ],
  },
  "la-2": {
    chunks: [
      "# 🇯🇵 Luyện Gọi Món Ăn Bằng Tiếng Nhật\n\n",
      "Sugoi! Gọi món bằng tiếng Nhật ở nhà hàng là kỹ năng thực tế cực kỳ hữu ích! ",
      "Mình sẽ dạy bạn từ cơ bản đến gọi được một bữa ăn hoàn chỉnh nhé.\n\n",
      "## 🍣 Từ vựng món ăn phổ biến\n\n",
      "| Tiếng Nhật | Romaji | Tiếng Việt |\n",
      "|-----------|--------|----------|\n",
      "| ラーメン | rāmen | Mì ramen |\n",
      "| 寿司 | sushi | Sushi |\n",
      "| 天ぷら | tempura | Tempura |\n",
      "| 牛丼 | gyūdon | Cơm bò |\n",
      "| お水 | omizu | Nước lọc |\n",
      "| ビール | bīru | Bia |\n\n",
      "## 🗣️ Mẫu câu gọi món\n\n",
      "**1. Khi vào nhà hàng:**\n",
      "- 「すみません」(Sumimasen) — Xin phép / Xin lỗi (gọi nhân viên)\n",
      "- 「二人です」(Futari desu) — Hai người ạ\n",
      "- 「メニューをください」(Menyū o kudasai) — Cho tôi xem menu\n\n",
      "**2. Gọi món:**\n",
      "- 「これをください」(Kore o kudasai) — Cho tôi cái này (chỉ vào menu)\n",
      "- 「ラーメンを一つお願いします」(Rāmen o hitotsu onegaishimasu) — Cho tôi một tô ramen\n",
      "- 「おすすめは何ですか？」(Osusume wa nan desu ka?) — Món gợi ý là gì?\n\n",
      "**3. Thanh toán:**\n",
      "- 「お会計お願いします」(Okaikei onegaishimasu) — Cho tôi tính tiền\n",
      "- 「ごちそうさまでした」(Gochisōsama deshita) — Cảm ơn bữa ăn (nói khi ra về)\n\n",
      "## 🎯 Thử luyện tập nào!\n",
      "Mình sẽ đóng vai nhân viên nhà hàng Nhật — bạn thử gọi một bữa ăn hoàn chỉnh nhé. Sẵn sàng chưa? いらっしゃいませ！(Irasshaimase — Chào mừng!) 🍱",
    ],
    widgets: [],
  },
  "la-3": {
    chunks: [
      "# 📝 Ôn Thi IELTS Speaking\n\n",
      "IELTS Speaking là phần nhiều bạn lo lắng nhất — nhưng đừng sợ! ",
      "Mình sẽ giúp bạn nắm vững cấu trúc và luyện tập hiệu quả nhé.\n\n",
      "## 📋 Cấu trúc bài thi Speaking\n\n",
      "| Part | Thời gian | Nội dung |\n",
      "|------|-----------|----------|\n",
      "| Part 1 | 4-5 phút | Câu hỏi về bản thân, sở thích |\n",
      "| Part 2 | 3-4 phút | Nói về 1 chủ đề (có 1 phút chuẩn bị) |\n",
      "| Part 3 | 4-5 phút | Thảo luận sâu về chủ đề Part 2 |\n\n",
      "## 🎯 Mẹo Vàng Cho Từng Part\n\n",
      "**Part 1 — Trả lời tự nhiên, đừng học thuộc:**\n",
      "- Trả lời 2-3 câu, có giải thích ngắn\n",
      "- Dùng cấu trúc: Answer + Reason + Example\n",
      "- Ví dụ: \"I love cooking because it helps me relax. Last week, I tried making pho from scratch.\"\n\n",
      "**Part 2 — Kỹ thuật ghi chú 1 phút:**\n",
      "- Ghi nhanh: WHO / WHAT / WHERE / WHEN / WHY / FEELING\n",
      "- Kể chuyện có mở đầu, diễn biến, kết thúc\n",
      "- Nói đủ 2 phút — tập đếm thời gian ở nhà\n\n",
      "**Part 3 — Thể hiện tư duy:**\n",
      "- Dùng cấu trúc: Opinion → Reason → Example → Contrast\n",
      "- Từ nối nâng band: \"Having said that\", \"From my perspective\", \"It's worth noting that\"\n\n",
      "## 🔥 Chủ đề thường gặp 2024\n",
      "Technology, Environment, Education, Health, Travel, Social Media, Work-life balance\n\n",
      "Bạn đang target band mấy? Mình sẽ luyện mock test theo đúng level cho bạn! Bắt đầu thử Part 1 luôn nhé? 🎤",
    ],
    widgets: [],
  },
  "mo-1": {
    chunks: [
      "# 🎥 Phim Kinh Dị Cho Buổi Hẹn Hò\n\n",
      "Hẹn hò xem phim kinh dị là chiêu kinh điển — sợ thì nắm tay thôi! 😂 ",
      "Mình chọn ra những bộ phim vừa đủ \"rợn\" mà không quá ghê, phù hợp xem đôi:\n\n",
      "<<WIDGET:playlist>>\n\n",
      "**Phân loại theo mức độ \"sợ\":**\n",
      "- 😱 **Sợ nhẹ (nắm tay):** A Quiet Place, Get Out — kịch tính hơn là jump scare\n",
      "- 😰 **Sợ vừa (ôm nhau):** The Conjuring, Insidious — kinh điển nhưng có cốt truyện hay\n",
      "- 💀 **Sợ nặng (cẩn thận nhé!):** Hereditary, It Follows — ám ảnh lâu dài\n\n",
      "**Mẹo:** Xem trên Netflix/Apple TV+ và chuẩn bị sẵn bỏng ngô + nến thơm — instant movie night! 🍿\n\n",
      "Hai bạn thuộc team \"sợ nhẹ\" hay \"càng sợ càng thích\"? Mình gợi ý thêm nhé! 👻",
    ],
    widgets: [
      {
        id: "w-playlist-4",
        type: "playlist",
        title: "Phim Kinh Dị Date Night",
        data: {
          tracks: [
            { title: "A Quiet Place", artist: "John Krasinski", duration: "1h 30m", bpm: 8.2 },
            { title: "Get Out", artist: "Jordan Peele", duration: "1h 44m", bpm: 8.5 },
            { title: "The Conjuring", artist: "James Wan", duration: "1h 52m", bpm: 7.5 },
            { title: "Insidious", artist: "James Wan", duration: "1h 43m", bpm: 7.0 },
            { title: "It Follows", artist: "David R. Mitchell", duration: "1h 40m", bpm: 6.8 },
            { title: "Hereditary", artist: "Ari Aster", duration: "2h 07m", bpm: 7.3 },
          ],
          mood: "horror",
          totalDuration: "~10 tiếng",
        },
      },
    ],
  },
  "mo-2": {
    chunks: [
      "# 🇻🇳 Phim Việt Nam Hay Nhất Năm 2024\n\n",
      "Năm 2024 là một năm bùng nổ của phim Việt đấy bạn! ",
      "Từ phòng vé đến chất lượng đều lên tầm mới. Xem danh sách mình tổng hợp nhé:\n\n",
      "<<WIDGET:playlist>>\n\n",
      "**Điểm sáng đáng chú ý:**\n",
      "- 🏆 **Mai** phá kỷ lục doanh thu phim Việt — Trấn Thành đạo diễn xuất sắc\n",
      "- 🎭 Dòng phim tâm lý xã hội đang chiếm spotlight\n",
      "- 🌍 Nhiều phim Việt lên sóng Netflix — khán giả quốc tế cũng mê!\n\n",
      "Bạn thích thể loại nào nhất? Tâm lý, hài, hay hành động? Mình gợi ý thêm cho bạn! 🎬",
    ],
    widgets: [
      {
        id: "w-playlist-5",
        type: "playlist",
        title: "Phim Việt Hay Nhất 2024",
        data: {
          tracks: [
            { title: "Mai", artist: "Trấn Thành", duration: "2h 11m", bpm: 8.0 },
            { title: "Đào, Phở và Piano", artist: "Phi Tiến Sơn", duration: "1h 47m", bpm: 7.2 },
            { title: "Lật Mặt 7", artist: "Lý Hải", duration: "2h 15m", bpm: 7.5 },
            { title: "Cô Dâu Hào Môn", artist: "Vũ Ngọc Đãng", duration: "1h 58m", bpm: 6.8 },
            { title: "Quật Mộ Trùng Ma", artist: "Trần Hữu Tấn", duration: "1h 50m", bpm: 6.5 },
            { title: "Án Tử", artist: "Nguyễn Hữu Hoàng", duration: "1h 52m", bpm: 7.0 },
          ],
          mood: "dramatic",
          totalDuration: "~12 tiếng",
        },
      },
    ],
  },
  "mo-3": {
    chunks: [
      "# ⚔️ Anime Tương Tự Attack on Titan\n\n",
      "AOT fan hả? Bạn có gu thẩm mỹ tốt lắm! ",
      "Mình chọn những anime có cùng \"vibe\" — cốt truyện sâu, plot twist điên đảo, và action mãn nhãn:\n\n",
      "<<WIDGET:playlist>>\n\n",
      "**Tại sao mình chọn những anime này:**\n",
      "- 🧠 **Cốt truyện phức tạp:** Vinland Saga, Code Geass — twist ngang AOT\n",
      "- ⚔️ **Chiến đấu mãn nhãn:** Demon Slayer, Jujutsu Kaisen — sakuga đỉnh cao\n",
      "- 🌑 **Dark & Mature:** Tokyo Ghoul, Psycho-Pass — không dành cho nhát gan\n",
      "- 📖 **World-building sâu:** Fullmetal Alchemist — huyền thoại vì lý do\n\n",
      "Bạn đã xem anime nào trong list rồi? Mình sẽ loại ra và gợi ý thêm những bộ khác! 🎌",
    ],
    widgets: [
      {
        id: "w-playlist-6",
        type: "playlist",
        title: "Anime như Attack on Titan",
        data: {
          tracks: [
            { title: "Vinland Saga", artist: "Wit Studio", duration: "24 tập", bpm: 8.8 },
            { title: "Fullmetal Alchemist: Brotherhood", artist: "Bones Studio", duration: "64 tập", bpm: 9.1 },
            { title: "Demon Slayer", artist: "Ufotable", duration: "44 tập", bpm: 8.6 },
            { title: "Jujutsu Kaisen", artist: "MAPPA", duration: "47 tập", bpm: 8.5 },
            { title: "Code Geass", artist: "Sunrise", duration: "50 tập", bpm: 8.7 },
            { title: "Tokyo Ghoul", artist: "Studio Pierrot", duration: "48 tập", bpm: 7.8 },
            { title: "Psycho-Pass", artist: "Production I.G", duration: "41 tập", bpm: 8.2 },
          ],
          mood: "intense",
          totalDuration: "~318 tập",
        },
      },
    ],
  },
  "we-2": {
    chunks: [
      "# 🏔️ Thời Điểm Tốt Nhất Để Đi Sapa Trekking\n\n",
      "Sapa trekking là trải nghiệm đỉnh của đỉnh — nhưng chọn đúng thời điểm mới \"sướng\"! ",
      "Mình phân tích thời tiết theo từng mùa cho bạn:\n\n",
      "<<WIDGET:weather>>\n\n",
      "Để bạn hình dung rõ hơn, đây là bản đồ các cung trek phổ biến:\n\n",
      "<<WIDGET:map>>\n\n",
      "**Mình gợi ý theo mục đích:**\n",
      "- 🌾 **Ruộng bậc thang vàng:** Tháng 9-10 — lúa chín vàng óng, đẹp nhất năm!\n",
      "- ❄️ **Săn tuyết:** Tháng 12-1 — may mắn gặp tuyết rơi ở đỉnh Fansipan\n",
      "- 🌸 **Hoa đào:** Tháng 1-2 — đẹp lãng mạn kiểu châu Âu\n",
      "- 🥾 **Trek dễ chịu nhất:** Tháng 3-5 — mát mẻ, ít mưa, tầm nhìn xa\n\n",
      "⚠️ **Tránh:** Tháng 6-8 — mưa nhiều, đường trơn trượt, hay sạt lở.\n\n",
      "Bạn dự định đi tháng mấy? Mình lên lịch trình trekking chi tiết cho bạn luôn! 🥾",
    ],
    widgets: [
      {
        id: "w-weather-2",
        type: "weather",
        title: "Thời tiết Sapa theo mùa",
        data: {
          location: "Sapa, Lào Cai",
          days: [
            {
              day: "Tháng 3-5",
              high: 22,
              low: 12,
              condition: "Mát mẻ, ít mưa",
              icon: "🌤️",
              humidity: 60,
              rain: 20,
            },
            {
              day: "Tháng 6-8",
              high: 25,
              low: 18,
              condition: "Mưa nhiều",
              icon: "🌧️",
              humidity: 90,
              rain: 80,
            },
            {
              day: "Tháng 9-10",
              high: 23,
              low: 14,
              condition: "Lúa chín vàng",
              icon: "🌾",
              humidity: 70,
              rain: 30,
            },
            {
              day: "Tháng 12-1",
              high: 10,
              low: 2,
              condition: "Rất lạnh, có tuyết",
              icon: "❄️",
              humidity: 80,
              rain: 15,
            },
          ],
        },
      },
      {
        id: "w-map-6",
        type: "map",
        title: "Bản đồ Trekking Sapa",
        data: {
          center: { lat: 22.336, lng: 103.844 },
          zoom: 12,
          markers: [
            { lat: 22.336, lng: 103.844, label: "Thị trấn Sapa", color: "#0EA5E9" },
            { lat: 22.303, lng: 103.775, label: "Bản Cát Cát", color: "#10B981" },
            { lat: 22.28, lng: 103.82, label: "Bản Tả Van", color: "#F97316" },
            { lat: 22.303, lng: 103.775, label: "Đỉnh Fansipan", color: "#EF4444" },
            { lat: 22.35, lng: 103.87, label: "Bản Tả Phìn", color: "#8B5CF6" },
          ],
        },
      },
    ],
  },
  "we-3": {
    chunks: [
      "# ⛅ So Sánh Thời Tiết Nha Trang và Phú Quốc Tuần Tới\n\n",
      "Đang phân vân giữa Nha Trang và Phú Quốc hả? ",
      "Để mình check thời tiết cả hai nơi giúp bạn quyết định nhanh nhé:\n\n",
      "<<WIDGET:weather>>\n\n",
      "**Tóm tắt nhanh:**\n",
      "- 🏖️ **Nha Trang:** Nắng nhiều hơn, nhiệt độ ổn định 28-32°C, biển lặng\n",
      "- 🌴 **Phú Quốc:** Có khả năng mưa rào chiều, nhưng sáng vẫn đẹp, ẩm hơn\n\n",
      "**Gợi ý của mình:**\n",
      "- ☀️ Nếu muốn **tắm biển + nắng gắt** → Nha Trang thắng\n",
      "- 🌅 Nếu muốn **resort chill + khám phá đảo** → Phú Quốc xịn hơn\n",
      "- 📸 Nếu muốn **ảnh đẹp hoàng hôn** → Phú Quốc nổi tiếng sunset!\n\n",
      "Bạn ưu tiên điều gì nhất cho chuyến đi? Mình tư vấn chi tiết hơn cho bạn! 🌊",
    ],
    widgets: [
      {
        id: "w-weather-3",
        type: "weather",
        title: "So sánh Nha Trang vs Phú Quốc",
        data: {
          location: "Nha Trang vs Phú Quốc",
          days: [
            {
              day: "Nha Trang - T2",
              high: 32,
              low: 25,
              condition: "Nắng",
              icon: "☀️",
              humidity: 55,
              rain: 5,
            },
            {
              day: "Nha Trang - T4",
              high: 31,
              low: 26,
              condition: "Nắng nhẹ mây",
              icon: "🌤️",
              humidity: 60,
              rain: 10,
            },
            {
              day: "Nha Trang - T6",
              high: 30,
              low: 25,
              condition: "Có mây",
              icon: "⛅",
              humidity: 65,
              rain: 15,
            },
            {
              day: "Phú Quốc - T2",
              high: 33,
              low: 27,
              condition: "Nắng nóng",
              icon: "☀️",
              humidity: 70,
              rain: 20,
            },
            {
              day: "Phú Quốc - T4",
              high: 32,
              low: 26,
              condition: "Mưa rào chiều",
              icon: "🌦️",
              humidity: 78,
              rain: 50,
            },
            {
              day: "Phú Quốc - T6",
              high: 31,
              low: 26,
              condition: "Mưa rào chiều",
              icon: "🌦️",
              humidity: 80,
              rain: 55,
            },
          ],
        },
      },
    ],
  },
};

export function getScriptedResponse(promptId: string): ScriptedResponse | null {
  return scriptedResponses[promptId] || null;
}
