import { Widget } from "./types";

interface ScriptedResponse {
  chunks: string[];
  widgets: Widget[];
}

export const scriptedResponses: Record<string, ScriptedResponse> = {
  "vp-1": {
    chunks: [
      "# 🏖️ Lịch Du Lịch Nha Trang 3 Ngày 2 Đêm - Lễ 30/4\n\n",
      "Tôi đã lên lịch trình chi tiết cho chuyến du lịch Nha Trang của bạn vào dịp lễ 30/4. ",
      "Đây là một hành trình tuyệt vời kết hợp giữa nghỉ dưỡng, khám phá, và ẩm thực!\n\n",
      "## Ngày 1: Đón Nha Trang\n",
      "- 🛬 **Sáng:** Bay đến sân bay Cam Ranh, xe đưa đón về khách sạn\n",
      "- 🏨 **Check-in:** VinPearl Resort & Spa Nha Trang\n",
      "- 🍜 **Trưa:** Thưởng thức bún chả cá tại quán Thanh Hiền\n",
      "- 🏊 **Chiều:** Tắm biển tại bãi Trần Phú, nghỉ ngơi tại resort\n",
      "- 🌅 **Tối:** Dạo phố đi bộ, thưởng thức hải sản tươi sống\n\n",
      "## Ngày 2: Khám Phá\n",
      "- 🎢 **Cả ngày:** VinWonders - công viên giải trí\n",
      "- 🐠 **Chiều:** Thủy cung VinPearl Aquarium\n",
      "- 🎵 **Tối:** Show nhạc nước tại Quảng trường\n\n",
      "## Ngày 3: Trải Nghiệm\n",
      "- 🤿 **Sáng:** Lặn ngắm san hô tại Hòn Mun\n",
      "- 🛍️ **Trưa:** Mua sắm đặc sản tại chợ Đầm\n",
      "- ✈️ **Chiều:** Trả phòng, bay về\n\n",
      "---\n\n",
      "Dưới đây là bản đồ các điểm tham quan và lịch trình chi tiết:\n\n",
      "<<WIDGET:map>>\n\n",
      "Và đây là lịch trình dạng timeline để bạn dễ theo dõi:\n\n",
      "<<WIDGET:itinerary>>\n\n",
      "💰 **Chi phí ước tính:** 8-12 triệu VNĐ/người (bao gồm vé máy bay, khách sạn, ăn uống, và vé tham quan)\n\n",
      "Bạn muốn tôi đặt phòng khách sạn hoặc tìm vé máy bay giá tốt không?",
    ],
    widgets: [
      {
        id: "w-map-1",
        type: "map",
        title: "Bản đồ Du lịch Nha Trang",
        data: {
          center: { lat: 12.2388, lng: 109.1967 },
          zoom: 13,
          markers: [
            {
              lat: 12.2388,
              lng: 109.1967,
              label: "Bãi biển Trần Phú",
              color: "#0EA5E9",
            },
            {
              lat: 12.2226,
              lng: 109.248,
              label: "VinPearl Resort",
              color: "#10B981",
            },
            {
              lat: 12.245,
              lng: 109.19,
              label: "Chợ Đầm",
              color: "#F97316",
            },
            {
              lat: 12.17,
              lng: 109.28,
              label: "Hòn Mun",
              color: "#8B5CF6",
            },
          ],
        },
      },
      {
        id: "w-itin-1",
        type: "itinerary",
        title: "Lịch trình 3 ngày Nha Trang",
        data: {
          days: [
            {
              day: 1,
              title: "Đón Nha Trang",
              items: [
                { time: "08:00", activity: "Bay đến Cam Ranh", icon: "✈️" },
                {
                  time: "11:00",
                  activity: "Check-in VinPearl Resort",
                  icon: "🏨",
                },
                {
                  time: "12:30",
                  activity: "Bún chả cá Thanh Hiền",
                  icon: "🍜",
                },
                {
                  time: "14:00",
                  activity: "Tắm biển Trần Phú",
                  icon: "🏊",
                },
                {
                  time: "18:00",
                  activity: "Phố đi bộ & hải sản",
                  icon: "🌅",
                },
              ],
            },
            {
              day: 2,
              title: "Khám Phá",
              items: [
                {
                  time: "09:00",
                  activity: "Công viên VinWonders",
                  icon: "🎢",
                },
                {
                  time: "15:00",
                  activity: "Thủy cung VinPearl",
                  icon: "🐠",
                },
                {
                  time: "19:00",
                  activity: "Show nhạc nước",
                  icon: "🎵",
                },
              ],
            },
            {
              day: 3,
              title: "Trải Nghiệm",
              items: [
                {
                  time: "07:00",
                  activity: "Lặn ngắm san hô Hòn Mun",
                  icon: "🤿",
                },
                {
                  time: "11:00",
                  activity: "Mua sắm chợ Đầm",
                  icon: "🛍️",
                },
                { time: "14:00", activity: "Bay về", icon: "✈️" },
              ],
            },
          ],
        },
      },
    ],
  },
  "vp-2": {
    chunks: [
      "# 🏨 Resort phù hợp gia đình ở Phú Quốc\n\n",
      "Lựa chọn tuyệt vời! Phú Quốc rất lý tưởng cho gia đình. ",
      "Đây là top resort với tiện ích gia đình xuất sắc:\n\n",
      "## 1. VinPearl Resort & Golf Phú Quốc\n",
      "⭐ 5 sao | Từ 4.200.000đ/đêm\n",
      "- Bãi biển riêng, câu lạc bộ trẻ em, công viên nước\n",
      "- Kết nối trực tiếp VinWonders\n\n",
      "## 2. InterContinental Phú Quốc\n",
      "⭐ 5 sao | Từ 5.800.000đ/đêm\n",
      "- Chương trình Planet Trekkers cho trẻ em\n",
      "- Nhiều hồ bơi bao gồm hồ trẻ em\n\n",
      "## 3. Novotel Phú Quốc Resort\n",
      "⭐ 4 sao | Từ 2.800.000đ/đêm\n",
      "- Phòng gia đình, sân chơi, hồ bơi trẻ em\n",
      "- Giá tốt cho gia đình\n\n",
      "<<WIDGET:map>>\n\n",
      "Bạn muốn tôi kiểm tra tình trạng phòng và giá cho ngày bạn muốn đi không?",
    ],
    widgets: [
      {
        id: "w-map-2",
        type: "map",
        title: "Bản đồ Resort Phú Quốc",
        data: {
          center: { lat: 10.29, lng: 103.98 },
          zoom: 11,
          markers: [
            {
              lat: 10.32,
              lng: 103.86,
              label: "VinPearl Resort",
              color: "#0EA5E9",
            },
            {
              lat: 10.17,
              lng: 104.01,
              label: "InterContinental",
              color: "#10B981",
            },
            {
              lat: 10.21,
              lng: 103.96,
              label: "Novotel",
              color: "#F97316",
            },
          ],
        },
      },
    ],
  },
  "mu-1": {
    chunks: [
      "# 🎧 Playlist Lo-Fi Chill cho Đêm Code Khuya\n\n",
      "Tôi đã chọn lọc playlist hoàn hảo giúp bạn tập trung. ",
      "Những bài hát này có BPM và âm thanh ambient phù hợp cho việc tập trung sâu.\n\n",
      "<<WIDGET:playlist>>\n\n",
      "**Tại sao những bài này phù hợp cho code:**\n",
      "- 🎵 Dải BPM: 70-85 (tối ưu cho tập trung)\n",
      "- 🎹 Ít lời hát để tránh mất tập trung\n",
      "- 🌙 Âm thanh ấm áp, ambient cho đêm khuya\n\n",
      "Playlist dài khoảng **2 tiếng** — hoàn hảo cho một phiên code tập trung. ",
      "Bạn muốn tôi điều chỉnh phong cách hoặc thêm bài không?",
    ],
    widgets: [
      {
        id: "w-playlist-1",
        type: "playlist",
        title: "Nhạc Lo-Fi Code Đêm Khuya",
        data: {
          tracks: [
            {
              title: "Snowfall",
              artist: "Øneheart & Reidenshi",
              duration: "2:14",
              bpm: 75,
            },
            {
              title: "Coffee Shop Vibes",
              artist: "Lo-Fi Dreamer",
              duration: "3:42",
              bpm: 80,
            },
            {
              title: "Midnight Rain",
              artist: "Sleepy Fish",
              duration: "2:58",
              bpm: 72,
            },
            {
              title: "2:00 AM Study Session",
              artist: "Mondo Loops",
              duration: "3:15",
              bpm: 78,
            },
            {
              title: "Tokyo Night Drive",
              artist: "DJ Autumn",
              duration: "4:01",
              bpm: 82,
            },
            {
              title: "Rainy Day in Seoul",
              artist: "Tomppabeats",
              duration: "2:45",
              bpm: 76,
            },
            {
              title: "Floating",
              artist: "Idealism",
              duration: "3:20",
              bpm: 70,
            },
            {
              title: "Quiet Moments",
              artist: "Kupla",
              duration: "2:55",
              bpm: 74,
            },
          ],
          mood: "chill",
          totalDuration: "2h 15m",
        },
      },
    ],
  },
  "fo-1": {
    chunks: [
      "# 🍲 Quán Phở Ngon Nhất Quận 1, TP.HCM\n\n",
      "Tôi đã tìm kiếm qua đánh giá, xếp hạng và gợi ý địa phương để tìm những quán phở ngon nhất Quận 1. ",
      "Đây là top gợi ý của tôi:\n\n",
      "## 1. Phở Hòa Pasteur ⭐ 4.5/5\n",
      "- 📍 260C Pasteur, Quận 3 (giáp Q1)\n",
      "- 💰 55.000 - 85.000 VNĐ\n",
      "- 🏆 **Huyền thoại** — phục vụ từ năm 1968\n",
      "- Nên thử: Phở tái nạm gầu\n\n",
      "## 2. Phở Lệ ⭐ 4.4/5\n",
      "- 📍 413 Nguyễn Trãi, Quận 5\n",
      "- 💰 65.000 - 95.000 VNĐ\n",
      "- 🏆 **Nước dùng đậm đà** — ninh xương 12 tiếng\n",
      "- Nên thử: Phở tái bò viên\n\n",
      "## 3. Phở Thìn Bò Hồ ⭐ 4.3/5\n",
      "- 📍 Chi nhánh Q1 (gốc 41 Lò Đúc)\n",
      "- 💰 60.000 - 80.000 VNĐ\n",
      "- 🏆 **Phong cách Hà Nội** — bò xào tái lăn\n\n",
      "<<WIDGET:map>>\n\n",
      "<<WIDGET:restaurant>>\n\n",
      "Bạn muốn tôi chỉ đường đến quán nào, hoặc tìm quán phù hợp chế độ ăn đặc biệt không?",
    ],
    widgets: [
      {
        id: "w-map-3",
        type: "map",
        title: "Phở ngon nhất Quận 1",
        data: {
          center: { lat: 10.776, lng: 106.695 },
          zoom: 14,
          markers: [
            {
              lat: 10.7821,
              lng: 106.694,
              label: "Phở Hòa Pasteur",
              color: "#EF4444",
            },
            {
              lat: 10.754,
              lng: 106.664,
              label: "Phở Lệ",
              color: "#F97316",
            },
            {
              lat: 10.779,
              lng: 106.7,
              label: "Phở Thìn Bò Hồ",
              color: "#10B981",
            },
          ],
        },
      },
      {
        id: "w-rest-1",
        type: "restaurant",
        title: "So sánh nhà hàng",
        data: {
          restaurants: [
            {
              name: "Phở Hòa Pasteur",
              rating: 4.5,
              price: "55-85K",
              specialty: "Phở Sài Gòn cổ điển từ 1968",
              hours: "6:00 - 24:00",
              distance: "0.8 km",
            },
            {
              name: "Phở Lệ",
              rating: 4.4,
              price: "65-95K",
              specialty: "Nước dùng ninh xương 12 tiếng",
              hours: "6:00 - 22:00",
              distance: "2.1 km",
            },
            {
              name: "Phở Thìn Bò Hồ",
              rating: 4.3,
              price: "60-80K",
              specialty: "Phở Hà Nội bò xào tái lăn",
              hours: "6:30 - 21:00",
              distance: "1.2 km",
            },
          ],
        },
      },
    ],
  },
  "sh-1": {
    chunks: [
      "# 📱 So sánh iPhone 15 Pro Max vs Samsung Galaxy S24 Ultra\n\n",
      "Để tôi phân tích chi tiết những điểm khác biệt quan trọng giúp bạn quyết định:\n\n",
      "## Hiệu năng\n",
      "- **iPhone 15 Pro Max:** Chip A17 Pro, 8GB RAM\n",
      "- **Galaxy S24 Ultra:** Snapdragon 8 Gen 3, 12GB RAM\n",
      "- 🏆 Hòa — cả hai đều là flagship đỉnh cao\n\n",
      "## Camera\n",
      "- **iPhone:** 48MP chính, 12MP góc siêu rộng, 12MP tele 5x\n",
      "- **Samsung:** 200MP chính, 12MP góc siêu rộng, 50MP tele 5x + 10MP tele 3x\n",
      "- 🏆 Samsung thắng về thông số, iPhone thắng về ổn định\n\n",
      "## Màn hình\n",
      "- **iPhone:** 6.7\" OLED, 2796x1290, 120Hz ProMotion\n",
      "- **Samsung:** 6.8\" AMOLED, 3120x1440, 120Hz Adaptive\n",
      "- 🏆 Samsung (độ phân giải cao hơn)\n\n",
      "## Tính năng AI\n",
      "- **iPhone:** Apple Intelligence, cải tiến Siri\n",
      "- **Samsung:** Galaxy AI, Circle to Search, Live Translate\n",
      "- 🏆 Samsung (nhiều tính năng AI hơn hiện tại)\n\n",
      "<<WIDGET:shopping>>\n\n",
      "**Khuyến nghị của tôi:** Nếu bạn đang dùng hệ sinh thái Apple, chọn iPhone. Nếu muốn camera specs tốt nhất và nhiều tính năng AI, Samsung thắng.\n\n",
      "Bạn muốn tôi tìm deal tốt nhất cho điện thoại nào không?",
    ],
    widgets: [
      {
        id: "w-shop-1",
        type: "shopping",
        title: "So sánh giá",
        data: {
          products: [
            {
              name: "iPhone 15 Pro Max 256GB",
              prices: [
                { store: "Apple Store", price: "34.990.000đ", url: "#" },
                { store: "Thế Giới Di Động", price: "33.490.000đ", url: "#" },
                { store: "CellphoneS", price: "32.990.000đ", url: "#" },
              ],
              image: "iphone",
            },
            {
              name: "Samsung Galaxy S24 Ultra 256GB",
              prices: [
                { store: "Samsung Store", price: "33.990.000đ", url: "#" },
                { store: "Thế Giới Di Động", price: "31.990.000đ", url: "#" },
                { store: "FPT Shop", price: "31.490.000đ", url: "#" },
              ],
              image: "samsung",
            },
          ],
        },
      },
    ],
  },
  "fi-1": {
    chunks: [
      "# 💪 Kế Hoạch Tập Luyện 4 Tuần Tại Nhà Cho Người Mới\n\n",
      "Chào mừng bạn đến với hành trình thể dục! Tôi đã thiết kế kế hoạch này theo từng bước, ",
      "bắt đầu nhẹ nhàng và tăng dần mỗi tuần. Không cần dụng cụ — chỉ cần bạn và một khoảng trống.\n\n",
      "## 📋 Tổng Quan Chương Trình\n",
      "- **Thời gian:** 4 tuần, 4 ngày/tuần\n",
      "- **Ngày nghỉ:** Thứ 4, Thứ 7, Chủ nhật\n",
      "- **Thời lượng mỗi buổi:** 25-40 phút\n",
      "- **Dụng cụ:** Không cần (chỉ tập với trọng lượng cơ thể)\n\n",
      "## Tuần 1: Nền Tảng\n",
      "| Ngày | Trọng tâm | Bài tập chính |\n",
      "|------|-----------|---------------|\n",
      "| T2 | Thân trên | Chống đẩy (biến thể), Plank giữ |\n",
      "| T3 | Thân dưới | Squat, Lunge, Nâng hông |\n",
      "| T5 | Core | Dead bugs, Bird dogs, Plank nghiêng |\n",
      "| T6 | Toàn thân | Circuit: Kết hợp tất cả |\n\n",
      "## Tuần 2-4: Tăng Dần Cường Độ\n",
      "Mỗi tuần thêm **2 reps mỗi set** và **5 giây cho các bài giữ**. ",
      "Đến tuần 4, bạn sẽ chống đẩy chuẩn và tập squat một chân!\n\n",
      "<<WIDGET:itinerary>>\n\n",
      "**Mẹo để thành công:**\n",
      "- 💧 Uống đủ nước — mục tiêu 2 lít/ngày\n",
      "- 😴 Ngủ 7-8 tiếng để phục hồi\n",
      "- 📸 Chụp ảnh tiến trình mỗi thứ 2\n\n",
      "Sẵn sàng bắt đầu chưa? Tôi có thể hướng dẫn chi tiết bài tập Ngày 1 với tư thế chuẩn!",
    ],
    widgets: [
      {
        id: "w-itin-2",
        type: "itinerary",
        title: "Lịch tập Tuần 1",
        data: {
          days: [
            {
              day: 1,
              title: "Thứ 2 - Thân Trên",
              items: [
                { time: "5 phút", activity: "Xoay tay & giãn cơ", icon: "🔄" },
                { time: "3x10", activity: "Chống đẩy biến thể", icon: "💪" },
                { time: "3x30s", activity: "Plank giữ", icon: "🧘" },
                { time: "3x10", activity: "Hít tay tricep (ghế)", icon: "🪑" },
                { time: "5 phút", activity: "Giãn cơ hồi phục", icon: "🧘‍♀️" },
              ],
            },
            {
              day: 2,
              title: "Thứ 3 - Thân Dưới",
              items: [
                { time: "5 phút", activity: "Khởi động động", icon: "🔄" },
                { time: "3x12", activity: "Squat", icon: "🦵" },
                { time: "3x10", activity: "Lunge đi bộ", icon: "🚶" },
                { time: "3x15", activity: "Nâng hông", icon: "🍑" },
                { time: "5 phút", activity: "Giãn cơ chân", icon: "🧘‍♂️" },
              ],
            },
          ],
        },
      },
    ],
  },
  "la-1": {
    chunks: [
      "# 🇻🇳 Câu Chào Hỏi Cơ Bản Tiếng Việt\n\n",
      "Xin chào! Hãy cùng học một số câu tiếng Việt cần thiết. ",
      "Tiếng Việt là ngôn ngữ thanh điệu với 6 thanh — nhưng đừng lo, chúng ta sẽ bắt đầu đơn giản!\n\n",
      "## Câu Chào Hỏi Cơ Bản\n\n",
      "| Tiếng Việt | Tiếng Anh | Phát âm gần đúng |\n",
      "|-----------|---------|-------------------|\n",
      "| Xin chào | Hello | sin chow |\n",
      "| Cảm ơn | Thank you | gahm uhn |\n",
      "| Xin lỗi | Sorry | sin loy |\n",
      "| Tạm biệt | Goodbye | tahm bee-et |\n",
      "| Vâng/Dạ | Yes | vuhng/yah |\n",
      "| Không | No | kohm |\n\n",
      "## Câu Lịch Sự\n",
      "- **Tôi tên là...** (toy ten lah) — My name is...\n",
      "- **Bạn khỏe không?** (bahn kwe kohm) — How are you?\n",
      "- **Tôi khỏe, cảm ơn** — I'm fine, thank you\n",
      "- **Rất vui được gặp bạn** — Nice to meet you\n\n",
      "## 🎯 Mẹo Văn Hóa\n",
      "Trong tiếng Việt, bạn nên dùng đại từ phù hợp tuổi tác:\n",
      "- **Anh/Chị** cho người lớn tuổi hơn\n",
      "- **Em** cho người nhỏ tuổi hơn\n",
      "- **Bạn** cho bạn bè cùng tuổi\n\n",
      "Bạn muốn luyện tập hội thoại sử dụng những câu này không? Tôi có thể đóng vai một tình huống cùng bạn!",
    ],
    widgets: [],
  },
  "we-1": {
    chunks: [
      "# 🌤️ Thời Tiết Đà Lạt Cuối Tuần Này\n\n",
      "Để tôi kiểm tra dự báo thời tiết cho bạn!\n\n",
      "<<WIDGET:weather>>\n\n",
      "## Tóm Tắt\n",
      "Đà Lạt sẽ **mát mẻ và có mây một phần** cuối tuần này — hoàn hảo cho hoạt động ngoài trời!\n\n",
      "## 🎯 Hoạt Động Được Gợi Ý\n",
      "Dựa trên thời tiết:\n",
      "- ☀️ **Sáng thứ 7:** Leo đỉnh Langbiang (trời quang dự kiến)\n",
      "- 🌿 **Chiều thứ 7:** Khám phá thác Datanla\n",
      "- 🌧️ **Sáng chủ nhật:** Cà phê hopping trong nhà (có thể mưa nhẹ)\n",
      "- 🌅 **Chiều chủ nhật:** Ngắm hoàng hôn ở Hồ Xuân Hương\n\n",
      "## 👕 Nên Mang Theo\n",
      "- Áo khoác nhẹ (nhiệt độ 15-22°C)\n",
      "- Áo mưa hoặc ô gấp gọn\n",
      "- Giày đi bộ thoải mái\n",
      "- Kem chống nắng (tia UV vẫn cao ở vùng cao)\n\n",
      "Bạn muốn tôi giúp lên kế hoạch cuối tuần chi tiết dựa trên thời tiết không?",
    ],
    widgets: [
      {
        id: "w-weather-1",
        type: "weather",
        title: "Dự Báo Cuối Tuần Đà Lạt",
        data: {
          location: "Đà Lạt, Lâm Đồng",
          days: [
            {
              day: "Thứ 7",
              high: 22,
              low: 15,
              condition: "Có mây",
              icon: "⛅",
              humidity: 65,
              rain: 10,
            },
            {
              day: "Chủ nhật",
              high: 20,
              low: 14,
              condition: "Mưa nhẹ",
              icon: "🌧️",
              humidity: 78,
              rain: 60,
            },
          ],
        },
      },
    ],
  },
};

export function getScriptedResponse(promptId: string): ScriptedResponse | null {
  return scriptedResponses[promptId] || null;
}
